application:
  title: "Spring Boot Project"
  version: "1.0"

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sbp-dev
    driverClassName: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  messages:
    basename: validation-messages

springdoc:
  api-docs:
    path: /api-docs